### Get Tooele Tech Route
GET http://localhost:3001/ttech HTTP/1.1


### Get the root Path / 
GET http://localhost:3001/ HTTP/1.1

### Get all students
GET http://localhost:3001/students 

### get one student
GET http://localhost:3001/students/63cedeaec646a3777ac82747

### create a student
POST http://localhost:3001/students HTTP/1.1
Content-Type: application/json

{
   "firstName": "Phil",
   "lastName": "Reeves",
   "email": "bowser@killer.com",
   "age": 42,
   "currentCollege": "Assassin's Academy"

}

